### ISSUE TITLE
how can i get the array data  in postgre ?

### ISSUE THREAD

**Issue by ktw1318** [terrier989/datastore#16]
I have some issue When I try to get array data in postgre as blow 

1. I made "array colum" in postgre right this

![image](https://user-images.githubusercontent.com/65937118/104986311-1fac3980-5a56-11eb-9fbb-7397a0fee840.png)

2. how ever, I can not get the data even see  , in console log and display 

![image](https://user-images.githubusercontent.com/65937118/104986618-c1338b00-5a56-11eb-8be2-f7b3136f35dd.png)

please anyone help me to fix the issue !

**Comment by ktw1318** [comment]
also it's not possible to get the data like " print(_sqlResult[0]['imgurl'][0]); "  how can i fix it?

**Comment by ktw1318** [comment]
anyone please help me ~~ >.<

**Comment by terrier989** [comment]
I close this because we are seeking a simpler, better design for the API and it will take some time before the package is ready for the public.
