### ISSUE TITLE
sounds like " Null safety"

### ISSUE THREAD

**Issue by ktw1318** [terrier989/datastore#17]
please new version sounds like " Null safety"

**Comment by finnjohnsen** [comment]
yes please, I was forced to choose another library because this isn't null safe.

**Comment by eric-taix** [comment]
> yes please, I was forced to choose another library because this isn't null safe.

Which package did you choose?

**Comment by ktw1318** [comment]
> > yes please, I was forced to choose another library because this isn't null safe.
> 
> Which package did you choose?

database 0.3.3 that is flutter database package

please null safety please

**Comment by eric-taix** [comment]
I was asking for the package you used to replace this one?

**Comment by terrier989** [comment]
I close this because we are seeking a simpler, better design for the API and it will take some time before the package (and adapters) are ready for the public.
