### ISSUE TITLE
is there any plan to update "this database version" ?

### ISSUE THREAD

**Issue by ItdaTeam** [terrier989/datastore#24]
First of all, thank you so much for making a good package. 

However, there are many problems because this package is not supported by dependence and null safety, so do you have any separate update plans?

I'm sure you're very busy, but I'd like to ask you to update the dependence issue and your safety support.

**Comment by terrier989** [comment]
I close this because we are seeking a simpler, better design for the API and it will take some time before the package (and adapters) are ready for the public.
