### ISSUE TITLE
Broken link in readme.md

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [terrier989/datastore#7]
in [Features](https://github.com/dint-dev/database/blob/master/README.md#features) it links to Dint, but it leads to a 404

**Comment by terrier989** [comment]
Thanks for reporting this. It points to [this](https://github.com/dint-dev/dint-dev.github.io) Github repository, which is work in progress. :)

**Comment by ThinkDigitalSoftware** [comment]
Ah, OK. No problem
